### ISSUE TITLE
creación de endpoints para leer e ingresar plan de adquisiciones a mongo

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_crud#10]
despues de la tarea #8 y #9  se requiere crear endpoint(servicios) que permitan ingresar el json a la base de datos de mongo y otro para leerlo, para la construcción se puede basar en el repo de `plan_cuentas_mongo_crud`

**Comment by Jeisson005** [comment]
Se crean endpoints para guardar un plan nuevo, obtener todos los planes, obtener un plan por ID, u obtener un plan por medio de una consulta.
NOTA: Las consultas se deben entregar en formato json, por ejemplo:
``` json
{ "vigencia": 2020 }
```
