### ISSUE TITLE
socialización y ajustes del modelo de base de datos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_crud#2]
en base al issue #1 se debe realizar la socialización de parte del equipo a los arquitectos,  dba y analista con el fin de recibir retro alimentación

esto con la finalidad de tener un modelo pulido para el viernes 23 de agosto

**Comment by BOTOOM** [comment]
en base al modelo realizado principalmente por @NeiderFajardo y socializado el día 26 de octubre del 2020 se realizan comentarios y aportes de parte de los dba @blacburn @fnrojash el arquitecto @corio27 y la analista @mcrubianot adicionalmente en la reunión se contó con la compañía de @ManuelMurillo y @steffanycruzs .

en base a los comentarios realizados la imagen adjunta corresponde al modelo con los ajustes para el plan de adquisiciones.

![plan_adquicisiones](https://user-images.githubusercontent.com/28914781/97257217-3fc7b600-17e3-11eb-8102-def69a54c0f3.png)


estaremos atentos a cualquier novedad , cambio o sugerencia

**Comment by blacburn** [comment]
Buen día, de acuerdo a los lineamientos de modelo de datos registrados en [https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md], se solicita realizar cambio sobre el nombramiento de los campos que son llaves foráneas referenciadas como id,  el nombramiento debe ser "nombreampo_id", muchas gracias.

**Comment by nodier25** [comment]
Buenos día 

se verifica el modelo y solo faltaria ajustar las recomendaciones hechas por el ing Andrey de las llaves foránes 

Muchas gracias

**Comment by BOTOOM** [comment]
se realizan los cambios ajustes comentados departe de @blacburn  y @nodier25 

![Plan_Adquisiciones](https://user-images.githubusercontent.com/28914781/97349468-83f79c80-185d-11eb-9f74-206b65216b8a.png)

se esta a la espera de la aprobación del arquitecto @corio27
