### ISSUE TITLE
proponer cambios para el modelo de datos de plan de adquisiciones con base es los cambios solicitados previamente

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_crud#35]
con base en el issue [listado de ajustes](https://github.com/udistrital/plan_adquisiciones_cliente/issues/61) se requiere proponer los ajustes a nivel de base de datos que puedan satisfacer las necesidades. Para completar la tarea se debe de modificar el modelo de datos entidad relación

**Comment by ManuelMurillo** [comment]
La propuesta de Cambios en el crud es la siguiente:

- Es necesario agregar una Tabla para las metas asociadas al renglon del plan
- Es necesario agregar una tabla para los productos asociados al plan
- Es necesario agregar una fuente de financiamiento para el registro de funcionamiento

**Comment by ManuelMurillo** [comment]
Aqui se comparte la propuesta del modelo para hacer el ajuste de los cambios:


Modelo:
https://drive.google.com/file/d/1yHbHd_VrLxPyxTY7ZlzyFmQqUJreBvcf/view?usp=sharing

![Plan_Adquisiciones_Propuesta](https://user-images.githubusercontent.com/29108085/107086927-ac7e2380-67c8-11eb-91c6-3d5e361a7aa2.png)
