### ISSUE TITLE
crear conexión  a mongo desde api crud

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_crud#8]
ya que para el historial de plan de adquisiciones se requiere: 

- [x] realizar la conexión a mongo db , para ello se puede usar como base el repositorio de [plan_cuentas_mongo_crud](https://github.com/udistrital/plan_cuentas_mongo_crud), en la carpeta `db` se realiza la conexión.

***ya que no hay datos a ingresar inicialmente no se requiere realizar migraciones***

- [x] agregar variable de entorno para mongo

- [x] añadir al docker-compose mongo y mongo-express asi como esta en el api mencionada anteriormente.

**Comment by Jeisson005** [comment]
Se realiza creación y dockerización
